spring:
  messages.basename: i18n/messages
  main:
    allow-circular-references: true

app:
  locale: en-EN
  questions-file-name: questions/questions
  questions-file-extension: .csv
  success-percent: 60